### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by denis-ilchishin** [denis-ilchishin/neemata#37]
### Features:
- [ ] ws ping/pong
- [ ] scheduler
- [ ] streaming server-to-client over ws
- [ ] streaming client-to-server over http
- [ ] graceful shutdown timeout
