### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by denis-ilchishin** [denis-ilchishin/neemata#40]
- ## Core
  - [ ] standartize API for adapters and clients 
  - [ ] add utils for testing

- ## Adapter: µWebSockets 
  - [ ] implement ping/pong
  - [ ] implement serving static assets

- ## Adapter: RabbitMQ
  - [ ] implement server-to-client events, besides basic rpc

- ## Extensions
  - ### Schema
    - [ ] implement configuration for custom JSON schema, e.g custom definitions
  - ### Queues
    - [ ] implement client-scope throttling
