### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by denny-il** [denis-ilchishin/neemata#49]
- ## Core
  - [x] #55
  - [x] #56
  - [x] #42
  - [x] #43
  - [x] #46
  - [x] #50
  - [x] #70
  - [x] #72
  - [x] #75
  - [x] #77
  - [x] #79
  - [ ] transport agnostic API documentation
  - [ ] rate limitting
  - [ ] custom data formats and serializers
  - [ ] scheduler/cron-runner
  - [ ] #47
  - [ ] resolve all todos
  - [ ] utils for testing
  - [ ] #80
  - [ ] library documentation

- ## Transport: Websockets (+HTTP)
  - [x] server-to-client streaming - #67
  - [x] client-to-server streaming - #67
  - [ ] ping/pong
  - [ ] static assets serving
 
- ## ~Transport: HTTP~ #78 

- ## Transport: AMQP
  - [ ] #73
  - [ ] server-to-client streaming - #71 
  - [ ] client-to-server streaming - #71
  - [ ] error handling and connection recovery
  - [ ] AMQP native timeouts

- ## Extensions
  - ### Schema
    - [ ] add configuration, e.g custom definitions
    - [ ] add support for events
    
---
### Other
  - load balancing strategies for API workers
  - HTTP/2
  - HTTP/3
  - WebTransport
